spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    # For Azure SQL, use the following instead:
    # url: jdbc:sqlserver://${DB_HOSTNAME}:1433;databaseName=your-database-name;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;authentication=ActiveDirectoryManagedIdentity;clientId=${AZURE_CLIENT_ID}
    # driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # username: ''
    # password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
